/* ===============================================
 *   This is an auto-generated file for KerbalVR. 
 *   Do not edit by hand.                         
 * ===============================================
 */

using System.IO;
using TMPro;
using Unity.Collections;
using UnityEngine;

namespace KerbalVR.Fonts {
    public class TMPFont_SpaceMono_Regular_SDF {
        public static TMPro.TMP_FontAsset GetInstance() {
            TMPro.TMP_FontAsset tmpFont = ScriptableObject.CreateInstance<TMPro.TMP_FontAsset>();
            tmpFont.name = "SpaceMono_Regular_SDF";
            tmpFont.hashCode = 0;
            tmpFont.materialHashCode = 0;
            tmpFont.fontAssetType = TMP_FontAsset.FontAssetTypes.SDF;
            tmpFont.normalStyle = 0.0f;
            tmpFont.normalSpacingOffset = 0.0f;
            tmpFont.boldStyle = 0.75f;
            tmpFont.boldSpacing = 7.0f;
            tmpFont.italicStyle = 35;
            tmpFont.tabSize = 10;
            tmpFont.AddFaceInfo(new FaceInfo() {
                Name = "Space Mono",
                PointSize = 43.0f,
                Scale = 1.0f,
                CharacterCount = 210,
                LineHeight = 63.6875f,
                Baseline = 0.0f,
                Ascender = 48.1875f,
                CapHeight = 30.125f,
                Descender = -15.5f,
                CenterLine = 0.0f,
                SuperscriptOffset = 48.1875f,
                SubscriptOffset = -4.3f,
                SubSize = 0.5f,
                Underline = -4.3f,
                UnderlineThickness = 2.15f,
                strikethrough = 11.886364f,
                strikethroughThickness = 2.15f,
                TabWidth = 263.125f,
                Padding = 5.0f,
                AtlasWidth = 512,
                AtlasHeight = 512,
            });
            TMP_Glyph[] glyphs = {
                new TMP_Glyph() {
                    id = 32,
                    x = 6.0f,
                    y = 517.0f,
                    width = 26.3125f,
                    height = 63.6875f,
                    xOffset = 0.0f,
                    yOffset = 48.1875f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 33,
                    x = 374.0f,
                    y = 349.0f,
                    width = 6.0625f,
                    height = 30.75f,
                    xOffset = 10.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 34,
                    x = 274.0f,
                    y = 147.0f,
                    width = 13.8125f,
                    height = 10.5625f,
                    xOffset = 6.1875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 35,
                    x = 453.0f,
                    y = 181.0f,
                    width = 20.3125f,
                    height = 21.3125f,
                    xOffset = 3.0f,
                    yOffset = 25.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 36,
                    x = 400.0f,
                    y = 307.0f,
                    width = 17.625f,
                    height = 27.6875f,
                    xOffset = 4.0f,
                    yOffset = 28.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 37,
                    x = 293.0f,
                    y = 105.0f,
                    width = 21.875f,
                    height = 30.625f,
                    xOffset = 2.1875f,
                    yOffset = 30.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 38,
                    x = 179.0f,
                    y = 55.0f,
                    width = 22.6875f,
                    height = 30.125f,
                    xOffset = 2.1875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 39,
                    x = 432.0f,
                    y = 412.0f,
                    width = 6.0625f,
                    height = 10.5625f,
                    xOffset = 10.125f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 40,
                    x = 6.0f,
                    y = 462.0f,
                    width = 16.8125f,
                    height = 43.5f,
                    xOffset = 6.6875f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 41,
                    x = 6.0f,
                    y = 407.0f,
                    width = 16.8125f,
                    height = 43.5f,
                    xOffset = 2.8125f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 42,
                    x = 453.0f,
                    y = 346.0f,
                    width = 21.3125f,
                    height = 21.3125f,
                    xOffset = 2.4375f,
                    yOffset = 25.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 43,
                    x = 133.0f,
                    y = 6.0f,
                    width = 17.9375f,
                    height = 18.0f,
                    xOffset = 4.125f,
                    yOffset = 24.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 44,
                    x = 475.0f,
                    y = 94.0f,
                    width = 6.0625f,
                    height = 10.625f,
                    xOffset = 10.125f,
                    yOffset = 5.4375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 45,
                    x = 360.0f,
                    y = 48.0f,
                    width = 12.9375f,
                    height = 3.125f,
                    xOffset = 6.6875f,
                    yOffset = 12.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 46,
                    x = 151.0f,
                    y = 207.0f,
                    width = 6.0625f,
                    height = 6.0625f,
                    xOffset = 10.125f,
                    yOffset = 5.4375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 47,
                    x = 55.0f,
                    y = 195.0f,
                    width = 15.5625f,
                    height = 39.25f,
                    xOffset = 5.375f,
                    yOffset = 34.6875f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 48,
                    x = 121.0f,
                    y = 163.0f,
                    width = 21.1875f,
                    height = 31.3125f,
                    xOffset = 2.5625f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 49,
                    x = 315.0f,
                    y = 63.0f,
                    width = 21.125f,
                    height = 30.125f,
                    xOffset = 2.5f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 50,
                    x = 280.0f,
                    y = 391.0f,
                    width = 20.875f,
                    height = 30.6875f,
                    xOffset = 2.75f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 51,
                    x = 355.0f,
                    y = 6.0f,
                    width = 21.1875f,
                    height = 30.75f,
                    xOffset = 2.6875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 52,
                    x = 191.0f,
                    y = 98.0f,
                    width = 22.1875f,
                    height = 30.125f,
                    xOffset = 2.0625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 53,
                    x = 253.0f,
                    y = 261.0f,
                    width = 21.4375f,
                    height = 30.75f,
                    xOffset = 2.8125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 54,
                    x = 194.0f,
                    y = 474.0f,
                    width = 20.9375f,
                    height = 31.3125f,
                    xOffset = 2.6875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 55,
                    x = 282.0f,
                    y = 349.0f,
                    width = 20.125f,
                    height = 30.125f,
                    xOffset = 3.0625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 56,
                    x = 159.0f,
                    y = 286.0f,
                    width = 20.9375f,
                    height = 31.3125f,
                    xOffset = 2.6875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 57,
                    x = 187.0f,
                    y = 338.0f,
                    width = 20.9375f,
                    height = 31.3125f,
                    xOffset = 2.6875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 58,
                    x = 396.0f,
                    y = 147.0f,
                    width = 6.0625f,
                    height = 22.5625f,
                    xOffset = 10.125f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 59,
                    x = 410.0f,
                    y = 268.0f,
                    width = 6.0625f,
                    height = 27.125f,
                    xOffset = 10.125f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 60,
                    x = 299.0f,
                    y = 147.0f,
                    width = 17.9375f,
                    height = 18.9375f,
                    xOffset = 4.125f,
                    yOffset = 24.5625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 61,
                    x = 84.0f,
                    y = 135.0f,
                    width = 17.9375f,
                    height = 9.25f,
                    xOffset = 4.125f,
                    yOffset = 19.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 62,
                    x = 486.0f,
                    y = 203.0f,
                    width = 17.9375f,
                    height = 18.9375f,
                    xOffset = 4.125f,
                    yOffset = 24.5625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 63,
                    x = 215.0f,
                    y = 388.0f,
                    width = 20.125f,
                    height = 31.3125f,
                    xOffset = 3.0625f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 64,
                    x = 453.0f,
                    y = 480.0f,
                    width = 22.625f,
                    height = 25.625f,
                    xOffset = 1.625f,
                    yOffset = 25.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 65,
                    x = 154.0f,
                    y = 97.0f,
                    width = 25.0625f,
                    height = 30.125f,
                    xOffset = 0.625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 66,
                    x = 262.0f,
                    y = 219.0f,
                    width = 21.0625f,
                    height = 30.125f,
                    xOffset = 2.4375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 67,
                    x = 154.0f,
                    y = 164.0f,
                    width = 21.1875f,
                    height = 31.3125f,
                    xOffset = 2.75f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 68,
                    x = 291.0f,
                    y = 307.0f,
                    width = 20.625f,
                    height = 30.125f,
                    xOffset = 3.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 69,
                    x = 314.0f,
                    y = 349.0f,
                    width = 18.5f,
                    height = 30.125f,
                    xOffset = 4.0f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 70,
                    x = 343.0f,
                    y = 391.0f,
                    width = 18.5f,
                    height = 30.125f,
                    xOffset = 4.0625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 71,
                    x = 126.0f,
                    y = 276.0f,
                    width = 21.125f,
                    height = 31.3125f,
                    xOffset = 2.5f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 72,
                    x = 319.0f,
                    y = 265.0f,
                    width = 20.0625f,
                    height = 30.125f,
                    xOffset = 3.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 73,
                    x = 292.0f,
                    y = 475.0f,
                    width = 19.0625f,
                    height = 30.125f,
                    xOffset = 3.5625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 74,
                    x = 292.0f,
                    y = 177.0f,
                    width = 21.1875f,
                    height = 30.75f,
                    xOffset = 3.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 75,
                    x = 326.0f,
                    y = 105.0f,
                    width = 21.1875f,
                    height = 30.125f,
                    xOffset = 3.8125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 76,
                    x = 323.0f,
                    y = 475.0f,
                    width = 19.3125f,
                    height = 30.125f,
                    xOffset = 3.6875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 77,
                    x = 224.0f,
                    y = 167.0f,
                    width = 22.3125f,
                    height = 30.125f,
                    xOffset = 1.9375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 78,
                    x = 328.0f,
                    y = 223.0f,
                    width = 20.0625f,
                    height = 30.125f,
                    xOffset = 3.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 79,
                    x = 153.0f,
                    y = 233.0f,
                    width = 21.1875f,
                    height = 31.3125f,
                    xOffset = 2.5625f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 80,
                    x = 312.0f,
                    y = 391.0f,
                    width = 20.0f,
                    height = 30.125f,
                    xOffset = 3.625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 81,
                    x = 93.0f,
                    y = 268.0f,
                    width = 21.1875f,
                    height = 37.375f,
                    xOffset = 2.5625f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 82,
                    x = 324.0f,
                    y = 433.0f,
                    width = 20.0f,
                    height = 30.125f,
                    xOffset = 3.625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 83,
                    x = 159.0f,
                    y = 424.0f,
                    width = 22.1875f,
                    height = 31.3125f,
                    xOffset = 1.875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 84,
                    x = 348.0f,
                    y = 63.0f,
                    width = 21.1875f,
                    height = 30.125f,
                    xOffset = 2.5625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 85,
                    x = 358.0f,
                    y = 181.0f,
                    width = 20.6875f,
                    height = 30.75f,
                    xOffset = 2.8125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 86,
                    x = 218.0f,
                    y = 253.0f,
                    width = 23.9375f,
                    height = 30.125f,
                    xOffset = 1.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 87,
                    x = 187.0f,
                    y = 167.0f,
                    width = 25.3125f,
                    height = 30.125f,
                    xOffset = 0.4375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 88,
                    x = 228.0f,
                    y = 211.0f,
                    width = 22.1875f,
                    height = 30.125f,
                    xOffset = 2.0625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 89,
                    x = 223.0f,
                    y = 303.0f,
                    width = 23.9375f,
                    height = 30.125f,
                    xOffset = 1.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 90,
                    x = 226.0f,
                    y = 475.0f,
                    width = 21.6875f,
                    height = 30.125f,
                    xOffset = 2.25f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 91,
                    x = 6.0f,
                    y = 242.0f,
                    width = 7.4375f,
                    height = 43.5f,
                    xOffset = 11.3125f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 92,
                    x = 28.0f,
                    y = 356.0f,
                    width = 15.5625f,
                    height = 39.25f,
                    xOffset = 5.375f,
                    yOffset = 34.6875f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 93,
                    x = 6.0f,
                    y = 187.0f,
                    width = 7.4375f,
                    height = 43.5f,
                    xOffset = 7.4375f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 94,
                    x = 242.0f,
                    y = 144.0f,
                    width = 20.125f,
                    height = 11.875f,
                    xOffset = 3.0625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 95,
                    x = 296.0f,
                    y = 45.0f,
                    width = 20.0625f,
                    height = 3.125f,
                    xOffset = 3.125f,
                    yOffset = -2.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 96,
                    x = 205.0f,
                    y = 38.0f,
                    width = 6.75f,
                    height = 5.0625f,
                    xOffset = 9.6875f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 97,
                    x = 328.0f,
                    y = 147.0f,
                    width = 22.8125f,
                    height = 22.5625f,
                    xOffset = 2.0f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 98,
                    x = 226.0f,
                    y = 433.0f,
                    width = 21.125f,
                    height = 30.75f,
                    xOffset = 2.9375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 99,
                    x = 453.0f,
                    y = 413.0f,
                    width = 21.125f,
                    height = 22.5625f,
                    xOffset = 2.5f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 100,
                    x = 247.0f,
                    y = 391.0f,
                    width = 21.0625f,
                    height = 30.75f,
                    xOffset = 2.5f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 101,
                    x = 421.0f,
                    y = 358.0f,
                    width = 20.5625f,
                    height = 22.5625f,
                    xOffset = 2.8125f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 102,
                    x = 355.0f,
                    y = 433.0f,
                    width = 18.875f,
                    height = 30.125f,
                    xOffset = 3.5f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 103,
                    x = 249.0f,
                    y = 349.0f,
                    width = 21.0625f,
                    height = 30.5625f,
                    xOffset = 2.1875f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 104,
                    x = 323.0f,
                    y = 307.0f,
                    width = 18.8125f,
                    height = 30.125f,
                    xOffset = 3.6875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 105,
                    x = 424.0f,
                    y = 475.0f,
                    width = 17.8125f,
                    height = 30.6875f,
                    xOffset = 4.25f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 106,
                    x = 28.0f,
                    y = 305.0f,
                    width = 14.1875f,
                    height = 39.3125f,
                    xOffset = 5.0f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 107,
                    x = 353.0f,
                    y = 307.0f,
                    width = 17.375f,
                    height = 30.125f,
                    xOffset = 5.875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 108,
                    x = 351.0f,
                    y = 265.0f,
                    width = 18.8125f,
                    height = 30.125f,
                    xOffset = 3.6875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 109,
                    x = 453.0f,
                    y = 447.0f,
                    width = 22.1875f,
                    height = 21.9375f,
                    xOffset = 2.0625f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 110,
                    x = 486.0f,
                    y = 368.0f,
                    width = 18.8125f,
                    height = 21.9375f,
                    xOffset = 3.6875f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 111,
                    x = 453.0f,
                    y = 379.0f,
                    width = 21.4375f,
                    height = 22.5625f,
                    xOffset = 2.4375f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 112,
                    x = 258.0f,
                    y = 307.0f,
                    width = 21.125f,
                    height = 30.5625f,
                    xOffset = 2.9375f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 113,
                    x = 286.0f,
                    y = 265.0f,
                    width = 21.0625f,
                    height = 30.5625f,
                    xOffset = 2.3125f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 114,
                    x = 453.0f,
                    y = 313.0f,
                    width = 21.875f,
                    height = 21.9375f,
                    xOffset = 2.0f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 115,
                    x = 486.0f,
                    y = 401.0f,
                    width = 18.125f,
                    height = 22.5625f,
                    xOffset = 3.75f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 116,
                    x = 360.0f,
                    y = 223.0f,
                    width = 18.3125f,
                    height = 30.125f,
                    xOffset = 3.0f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 117,
                    x = 486.0f,
                    y = 335.0f,
                    width = 18.8125f,
                    height = 21.9375f,
                    xOffset = 3.4375f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 118,
                    x = 453.0f,
                    y = 280.0f,
                    width = 21.5f,
                    height = 21.3125f,
                    xOffset = 2.3125f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 119,
                    x = 253.0f,
                    y = 6.0f,
                    width = 24.8125f,
                    height = 21.3125f,
                    xOffset = 0.75f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 120,
                    x = 485.0f,
                    y = 170.0f,
                    width = 20.1875f,
                    height = 21.3125f,
                    xOffset = 3.0f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 121,
                    x = 487.0f,
                    y = 476.0f,
                    width = 18.8125f,
                    height = 29.9375f,
                    xOffset = 3.6875f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 122,
                    x = 486.0f,
                    y = 302.0f,
                    width = 18.5625f,
                    height = 21.3125f,
                    xOffset = 3.875f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 123,
                    x = 6.0f,
                    y = 352.0f,
                    width = 10.8125f,
                    height = 43.5f,
                    xOffset = 8.5625f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 124,
                    x = 6.0f,
                    y = 132.0f,
                    width = 3.0625f,
                    height = 43.5f,
                    xOffset = 11.5625f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 125,
                    x = 6.0f,
                    y = 297.0f,
                    width = 10.8125f,
                    height = 43.5f,
                    xOffset = 6.875f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 126,
                    x = 119.0f,
                    y = 206.0f,
                    width = 20.875f,
                    height = 7.375f,
                    xOffset = 2.6875f,
                    yOffset = 17.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 160,
                    x = 6.0f,
                    y = 517.0f,
                    width = 0.0f,
                    height = 0.0f,
                    xOffset = 0.0f,
                    yOffset = 0.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 161,
                    x = 382.0f,
                    y = 307.0f,
                    width = 6.0625f,
                    height = 30.75f,
                    xOffset = 10.125f,
                    yOffset = 22.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 162,
                    x = 322.0f,
                    y = 6.0f,
                    width = 21.1875f,
                    height = 27.6875f,
                    xOffset = 2.5625f,
                    yOffset = 28.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 163,
                    x = 396.0f,
                    y = 198.0f,
                    width = 16.8125f,
                    height = 21.9375f,
                    xOffset = 4.6875f,
                    yOffset = 26.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 164,
                    x = 362.0f,
                    y = 147.0f,
                    width = 22.5625f,
                    height = 22.5f,
                    xOffset = 1.875f,
                    yOffset = 26.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 165,
                    x = 486.0f,
                    y = 269.0f,
                    width = 18.0625f,
                    height = 21.3125f,
                    xOffset = 4.125f,
                    yOffset = 25.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 166,
                    x = 6.0f,
                    y = 77.0f,
                    width = 3.0625f,
                    height = 43.5f,
                    xOffset = 11.5625f,
                    yOffset = 36.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 167,
                    x = 414.0f,
                    y = 148.0f,
                    width = 11.75f,
                    height = 21.3125f,
                    xOffset = 7.375f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 168,
                    x = 179.0f,
                    y = 38.0f,
                    width = 14.5625f,
                    height = 6.0f,
                    xOffset = 5.8125f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 169,
                    x = 453.0f,
                    y = 247.0f,
                    width = 21.3125f,
                    height = 21.3125f,
                    xOffset = 2.4375f,
                    yOffset = 34.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 170,
                    x = 133.0f,
                    y = 139.0f,
                    width = 13.6875f,
                    height = 12.9375f,
                    xOffset = 6.75f,
                    yOffset = 30.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 171,
                    x = 191.0f,
                    y = 6.0f,
                    width = 19.5625f,
                    height = 20.3125f,
                    xOffset = 3.3125f,
                    yOffset = 20.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 172,
                    x = 39.0f,
                    y = 6.0f,
                    width = 17.9375f,
                    height = 6.75f,
                    xOffset = 4.125f,
                    yOffset = 16.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 174,
                    x = 453.0f,
                    y = 214.0f,
                    width = 21.3125f,
                    height = 21.3125f,
                    xOffset = 2.4375f,
                    yOffset = 34.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 175,
                    x = 384.0f,
                    y = 49.0f,
                    width = 12.125f,
                    height = 2.875f,
                    xOffset = 7.0625f,
                    yOffset = 27.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 176,
                    x = 169.0f,
                    y = 209.0f,
                    width = 12.4375f,
                    height = 12.4375f,
                    xOffset = 6.875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 177,
                    x = 486.0f,
                    y = 233.0f,
                    width = 17.9375f,
                    height = 24.0625f,
                    xOffset = 4.125f,
                    yOffset = 24.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 178,
                    x = 182.0f,
                    y = 140.0f,
                    width = 8.8125f,
                    height = 12.6875f,
                    xOffset = 8.75f,
                    yOffset = 30.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 179,
                    x = 202.0f,
                    y = 143.0f,
                    width = 8.8125f,
                    height = 12.6875f,
                    xOffset = 8.75f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 180,
                    x = 223.0f,
                    y = 39.0f,
                    width = 6.75f,
                    height = 5.0625f,
                    xOffset = 9.875f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 181,
                    x = 487.0f,
                    y = 435.0f,
                    width = 18.8125f,
                    height = 29.9375f,
                    xOffset = 3.6875f,
                    yOffset = 21.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 182,
                    x = 428.0f,
                    y = 259.0f,
                    width = 14.0f,
                    height = 21.3125f,
                    xOffset = 5.3125f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 183,
                    x = 241.0f,
                    y = 39.0f,
                    width = 6.0625f,
                    height = 6.0f,
                    xOffset = 10.125f,
                    yOffset = 18.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 184,
                    x = 113.0f,
                    y = 135.0f,
                    width = 8.1875f,
                    height = 9.125f,
                    xOffset = 9.0625f,
                    yOffset = 0.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 185,
                    x = 222.0f,
                    y = 143.0f,
                    width = 9.0f,
                    height = 12.4375f,
                    xOffset = 8.9375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 186,
                    x = 158.0f,
                    y = 140.0f,
                    width = 12.8125f,
                    height = 12.9375f,
                    xOffset = 6.75f,
                    yOffset = 30.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 187,
                    x = 222.0f,
                    y = 6.0f,
                    width = 19.5625f,
                    height = 20.3125f,
                    xOffset = 3.3125f,
                    yOffset = 20.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 188,
                    x = 295.0f,
                    y = 223.0f,
                    width = 21.625f,
                    height = 30.125f,
                    xOffset = 2.1875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 189,
                    x = 325.0f,
                    y = 181.0f,
                    width = 21.625f,
                    height = 30.125f,
                    xOffset = 2.1875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 190,
                    x = 359.0f,
                    y = 105.0f,
                    width = 21.8125f,
                    height = 30.125f,
                    xOffset = 2.0625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 191,
                    x = 186.0f,
                    y = 243.0f,
                    width = 20.0625f,
                    height = 31.3125f,
                    xOffset = 3.0625f,
                    yOffset = 22.1875f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 192,
                    x = 54.0f,
                    y = 306.0f,
                    width = 25.0625f,
                    height = 38.3125f,
                    xOffset = 0.625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 193,
                    x = 56.0f,
                    y = 256.0f,
                    width = 25.0625f,
                    height = 38.3125f,
                    xOffset = 0.625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 194,
                    x = 82.0f,
                    y = 206.0f,
                    width = 25.0625f,
                    height = 38.3125f,
                    xOffset = 0.625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 195,
                    x = 84.0f,
                    y = 156.0f,
                    width = 25.0625f,
                    height = 39.0f,
                    xOffset = 0.625f,
                    yOffset = 39.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 196,
                    x = 43.0f,
                    y = 32.0f,
                    width = 25.0625f,
                    height = 39.4375f,
                    xOffset = 0.625f,
                    yOffset = 39.5f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 197,
                    x = 6.0f,
                    y = 24.0f,
                    width = 25.0625f,
                    height = 42.0f,
                    xOffset = 0.625f,
                    yOffset = 42.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 198,
                    x = 213.0f,
                    y = 56.0f,
                    width = 22.875f,
                    height = 30.125f,
                    xOffset = 0.625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 199,
                    x = 53.0f,
                    y = 84.0f,
                    width = 21.1875f,
                    height = 39.8125f,
                    xOffset = 2.75f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 200,
                    x = 91.0f,
                    y = 317.0f,
                    width = 18.5f,
                    height = 38.3125f,
                    xOffset = 4.0f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 201,
                    x = 118.0f,
                    y = 367.0f,
                    width = 18.5f,
                    height = 38.3125f,
                    xOffset = 4.0f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 202,
                    x = 129.0f,
                    y = 417.0f,
                    width = 18.5f,
                    height = 38.3125f,
                    xOffset = 4.0f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 203,
                    x = 25.0f,
                    y = 195.0f,
                    width = 18.5f,
                    height = 39.4375f,
                    xOffset = 4.0f,
                    yOffset = 39.5f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 204,
                    x = 87.0f,
                    y = 367.0f,
                    width = 19.0625f,
                    height = 38.3125f,
                    xOffset = 3.5625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 205,
                    x = 98.0f,
                    y = 417.0f,
                    width = 19.0625f,
                    height = 38.3125f,
                    xOffset = 3.5625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 206,
                    x = 99.0f,
                    y = 467.0f,
                    width = 19.0625f,
                    height = 38.3125f,
                    xOffset = 3.5625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 207,
                    x = 25.0f,
                    y = 246.0f,
                    width = 19.0625f,
                    height = 39.4375f,
                    xOffset = 3.5625f,
                    yOffset = 39.5f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 208,
                    x = 392.0f,
                    y = 105.0f,
                    width = 20.625f,
                    height = 30.125f,
                    xOffset = 3.125f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 209,
                    x = 34.0f,
                    y = 417.0f,
                    width = 20.0625f,
                    height = 39.0f,
                    xOffset = 3.125f,
                    yOffset = 39.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 210,
                    x = 113.0f,
                    y = 35.0f,
                    width = 21.1875f,
                    height = 38.9375f,
                    xOffset = 2.5625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 211,
                    x = 121.0f,
                    y = 85.0f,
                    width = 21.1875f,
                    height = 38.9375f,
                    xOffset = 2.5625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 212,
                    x = 146.0f,
                    y = 35.0f,
                    width = 21.1875f,
                    height = 38.9375f,
                    xOffset = 2.5625f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 213,
                    x = 80.0f,
                    y = 33.0f,
                    width = 21.1875f,
                    height = 39.625f,
                    xOffset = 2.5625f,
                    yOffset = 39.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 214,
                    x = 21.0f,
                    y = 135.0f,
                    width = 21.1875f,
                    height = 40.0625f,
                    xOffset = 2.5625f,
                    yOffset = 39.5f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 215,
                    x = 162.0f,
                    y = 7.0f,
                    width = 17.0625f,
                    height = 17.0f,
                    xOffset = 4.625f,
                    yOffset = 23.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 216,
                    x = 121.0f,
                    y = 319.0f,
                    width = 21.1875f,
                    height = 37.0f,
                    xOffset = 2.5625f,
                    yOffset = 33.3125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 217,
                    x = 55.0f,
                    y = 367.0f,
                    width = 20.6875f,
                    height = 38.9375f,
                    xOffset = 2.8125f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 218,
                    x = 66.0f,
                    y = 417.0f,
                    width = 20.6875f,
                    height = 38.9375f,
                    xOffset = 2.8125f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 219,
                    x = 67.0f,
                    y = 467.0f,
                    width = 20.6875f,
                    height = 38.9375f,
                    xOffset = 2.8125f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 220,
                    x = 21.0f,
                    y = 83.0f,
                    width = 20.6875f,
                    height = 40.0625f,
                    xOffset = 2.8125f,
                    yOffset = 39.5f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 221,
                    x = 86.0f,
                    y = 85.0f,
                    width = 23.9375f,
                    height = 38.3125f,
                    xOffset = 1.125f,
                    yOffset = 38.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 222,
                    x = 354.0f,
                    y = 475.0f,
                    width = 20.0f,
                    height = 30.125f,
                    xOffset = 3.625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 223,
                    x = 160.0f,
                    y = 474.0f,
                    width = 22.5625f,
                    height = 31.3125f,
                    xOffset = 1.625f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 224,
                    x = 225.0f,
                    y = 101.0f,
                    width = 22.8125f,
                    height = 30.1875f,
                    xOffset = 2.0f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 225,
                    x = 258.0f,
                    y = 169.0f,
                    width = 22.8125f,
                    height = 30.1875f,
                    xOffset = 2.0f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 226,
                    x = 247.0f,
                    y = 59.0f,
                    width = 22.8125f,
                    height = 30.1875f,
                    xOffset = 2.0f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 227,
                    x = 259.0f,
                    y = 102.0f,
                    width = 22.8125f,
                    height = 30.875f,
                    xOffset = 2.0f,
                    yOffset = 30.25f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 228,
                    x = 119.0f,
                    y = 225.0f,
                    width = 22.8125f,
                    height = 31.3125f,
                    xOffset = 2.0f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 229,
                    x = 148.0f,
                    y = 372.0f,
                    width = 22.8125f,
                    height = 33.9375f,
                    xOffset = 2.0f,
                    yOffset = 33.3125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 230,
                    x = 396.0f,
                    y = 231.0f,
                    width = 20.125f,
                    height = 22.5625f,
                    xOffset = 3.0625f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 231,
                    x = 154.0f,
                    y = 329.0f,
                    width = 21.125f,
                    height = 31.0625f,
                    xOffset = 2.5f,
                    yOffset = 21.9375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 232,
                    x = 414.0f,
                    y = 63.0f,
                    width = 20.5625f,
                    height = 30.1875f,
                    xOffset = 2.8125f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 233,
                    x = 421.0f,
                    y = 21.0f,
                    width = 20.5625f,
                    height = 30.1875f,
                    xOffset = 2.8125f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 234,
                    x = 292.0f,
                    y = 433.0f,
                    width = 20.5625f,
                    height = 30.1875f,
                    xOffset = 2.8125f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 235,
                    x = 191.0f,
                    y = 295.0f,
                    width = 20.5625f,
                    height = 31.3125f,
                    xOffset = 2.8125f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 236,
                    x = 424.0f,
                    y = 434.0f,
                    width = 17.8125f,
                    height = 29.5625f,
                    xOffset = 4.25f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 237,
                    x = 392.0f,
                    y = 350.0f,
                    width = 17.8125f,
                    height = 29.5625f,
                    xOffset = 4.25f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 238,
                    x = 403.0f,
                    y = 392.0f,
                    width = 17.8125f,
                    height = 29.5625f,
                    xOffset = 4.25f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 239,
                    x = 381.0f,
                    y = 265.0f,
                    width = 17.8125f,
                    height = 30.6875f,
                    xOffset = 4.25f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 240,
                    x = 182.0f,
                    y = 381.0f,
                    width = 21.4375f,
                    height = 31.6875f,
                    xOffset = 2.4375f,
                    yOffset = 31.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 241,
                    x = 344.0f,
                    y = 349.0f,
                    width = 18.8125f,
                    height = 30.125f,
                    xOffset = 3.6875f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 242,
                    x = 381.0f,
                    y = 63.0f,
                    width = 21.4375f,
                    height = 30.1875f,
                    xOffset = 2.4375f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 243,
                    x = 388.0f,
                    y = 7.0f,
                    width = 21.4375f,
                    height = 30.1875f,
                    xOffset = 2.4375f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 244,
                    x = 259.0f,
                    y = 475.0f,
                    width = 21.4375f,
                    height = 30.1875f,
                    xOffset = 2.4375f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 245,
                    x = 259.0f,
                    y = 433.0f,
                    width = 21.4375f,
                    height = 30.75f,
                    xOffset = 2.4375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 246,
                    x = 193.0f,
                    y = 431.0f,
                    width = 21.4375f,
                    height = 31.3125f,
                    xOffset = 2.4375f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 247,
                    x = 424.0f,
                    y = 199.0f,
                    width = 17.9375f,
                    height = 20.3125f,
                    xOffset = 4.125f,
                    yOffset = 25.25f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 248,
                    x = 289.0f,
                    y = 6.0f,
                    width = 21.4375f,
                    height = 26.9375f,
                    xOffset = 2.4375f,
                    yOffset = 24.0f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 249,
                    x = 373.0f,
                    y = 391.0f,
                    width = 18.8125f,
                    height = 30.1875f,
                    xOffset = 3.4375f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 250,
                    x = 385.0f,
                    y = 433.0f,
                    width = 18.8125f,
                    height = 30.1875f,
                    xOffset = 3.4375f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 251,
                    x = 385.0f,
                    y = 475.0f,
                    width = 18.8125f,
                    height = 30.1875f,
                    xOffset = 3.4375f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 252,
                    x = 219.0f,
                    y = 345.0f,
                    width = 18.8125f,
                    height = 31.3125f,
                    xOffset = 3.4375f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 253,
                    x = 130.0f,
                    y = 467.0f,
                    width = 18.8125f,
                    height = 38.1875f,
                    xOffset = 3.6875f,
                    yOffset = 29.625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 254,
                    x = 34.0f,
                    y = 467.0f,
                    width = 21.125f,
                    height = 38.75f,
                    xOffset = 2.9375f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 255,
                    x = 54.0f,
                    y = 144.0f,
                    width = 18.8125f,
                    height = 39.3125f,
                    xOffset = 3.6875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8211,
                    x = 328.0f,
                    y = 48.0f,
                    width = 20.0625f,
                    height = 3.125f,
                    xOffset = 3.125f,
                    yOffset = 12.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8212,
                    x = 259.0f,
                    y = 44.0f,
                    width = 25.3125f,
                    height = 3.125f,
                    xOffset = 0.5f,
                    yOffset = 12.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8216,
                    x = 453.0f,
                    y = 93.0f,
                    width = 6.0625f,
                    height = 10.5625f,
                    xOffset = 10.125f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8217,
                    x = 493.0f,
                    y = 94.0f,
                    width = 6.0625f,
                    height = 10.5625f,
                    xOffset = 10.125f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8218,
                    x = 446.0f,
                    y = 71.0f,
                    width = 6.0625f,
                    height = 10.5625f,
                    xOffset = 10.125f,
                    yOffset = 6.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8220,
                    x = 428.0f,
                    y = 237.0f,
                    width = 13.8125f,
                    height = 10.5625f,
                    xOffset = 6.1875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8221,
                    x = 453.0f,
                    y = 159.0f,
                    width = 13.8125f,
                    height = 10.5625f,
                    xOffset = 6.1875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8222,
                    x = 478.0f,
                    y = 148.0f,
                    width = 13.8125f,
                    height = 10.5625f,
                    xOffset = 6.1875f,
                    yOffset = 6.0625f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8224,
                    x = 429.0f,
                    y = 325.0f,
                    width = 12.9375f,
                    height = 21.3125f,
                    xOffset = 6.6875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8225,
                    x = 429.0f,
                    y = 292.0f,
                    width = 12.9375f,
                    height = 21.3125f,
                    xOffset = 6.6875f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8226,
                    x = 453.0f,
                    y = 115.0f,
                    width = 10.1875f,
                    height = 10.125f,
                    xOffset = 8.0625f,
                    yOffset = 20.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8230,
                    x = 6.0f,
                    y = 6.0f,
                    width = 21.1875f,
                    height = 6.0625f,
                    xOffset = 2.5625f,
                    yOffset = 5.4375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8240,
                    x = 281.0f,
                    y = 60.0f,
                    width = 22.75f,
                    height = 30.625f,
                    xOffset = 1.875f,
                    yOffset = 30.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8242,
                    x = 500.0f,
                    y = 126.0f,
                    width = 6.0f,
                    height = 10.5625f,
                    xOffset = 10.375f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8243,
                    x = 453.0f,
                    y = 137.0f,
                    width = 13.875f,
                    height = 10.5625f,
                    xOffset = 6.4375f,
                    yOffset = 30.75f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8249,
                    x = 424.0f,
                    y = 116.0f,
                    width = 10.3125f,
                    height = 20.3125f,
                    xOffset = 7.9375f,
                    yOffset = 20.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8250,
                    x = 478.0f,
                    y = 116.0f,
                    width = 10.3125f,
                    height = 20.3125f,
                    xOffset = 7.9375f,
                    yOffset = 20.8125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8260,
                    x = 68.0f,
                    y = 8.0f,
                    width = 21.375f,
                    height = 12.375f,
                    xOffset = 2.4375f,
                    yOffset = 21.25f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8364,
                    x = 193.0f,
                    y = 209.0f,
                    width = 23.1875f,
                    height = 22.5f,
                    xOffset = 1.5f,
                    yOffset = 26.375f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8482,
                    x = 101.0f,
                    y = 9.0f,
                    width = 20.3125f,
                    height = 12.4375f,
                    xOffset = 2.625f,
                    yOffset = 30.125f,
                    xAdvance = 26.3125f,
                    scale = 1.0f,
                },
            };
            tmpFont.AddGlyphInfo(glyphs);
            tmpFont.SortGlyphs();
            Texture2D tmpTexture = new Texture2D(512, 512, TextureFormat.Alpha8, false);
            tmpTexture.name = "SpaceMono_Regular_SDF Atlas";
            string textureFilePath = Path.Combine(KSPUtil.ApplicationRootPath, "GameData", KerbalVR.Globals.KERBALVR_TEXTURES_DIR, "SpaceMono_Regular_SDF_Texture.bin");
            byte[] textureBytes = File.ReadAllBytes(textureFilePath);
            NativeArray<byte> textureData = tmpTexture.GetRawTextureData<byte>();
            textureData.CopyFrom(textureBytes);
            tmpTexture.Apply();
            tmpFont.atlas = tmpTexture;
            Material tmpMaterial = new Material(Shader.Find("TextMeshPro/Distance Field"));
            tmpMaterial.name = "SpaceMono_Regular_SDF Material";
            tmpMaterial.mainTexture = tmpTexture;
            tmpFont.material = tmpMaterial;
            tmpFont.AddKerningInfo(new KerningTable());
            tmpFont.ReadFontDefinition();
            return tmpFont;
        }
    }
}
