/* ===============================================
 *   This is an auto-generated file for KerbalVR. 
 *   Do not edit by hand.                         
 * ===============================================
 */

using System.IO;
using TMPro;
using Unity.Collections;
using UnityEngine;

namespace KerbalVR.Fonts {
    public class TMPFont_Futura_Medium_BT_SDF {
        public static TMPro.TMP_FontAsset GetInstance() {
            TMPro.TMP_FontAsset tmpFont = ScriptableObject.CreateInstance<TMPro.TMP_FontAsset>();
            tmpFont.name = "Futura_Medium_BT_SDF";
            tmpFont.hashCode = 0;
            tmpFont.materialHashCode = 0;
            tmpFont.fontAssetType = TMP_FontAsset.FontAssetTypes.SDF;
            tmpFont.normalStyle = 0.0f;
            tmpFont.normalSpacingOffset = 0.0f;
            tmpFont.boldStyle = 0.75f;
            tmpFont.boldSpacing = 7.0f;
            tmpFont.italicStyle = 35;
            tmpFont.tabSize = 10;
            tmpFont.AddFaceInfo(new FaceInfo() {
                Name = "Futura Md BT",
                PointSize = 40.0f,
                Scale = 0.0f,
                CharacterCount = 207,
                LineHeight = 47.9375f,
                Baseline = 0.0f,
                Ascender = 38.5625f,
                CapHeight = 0.0f,
                Descender = -9.4375f,
                CenterLine = 0.0f,
                SuperscriptOffset = 38.5625f,
                SubscriptOffset = -5.7617188f,
                SubSize = 0.5f,
                Underline = -5.7617188f,
                UnderlineThickness = 2.8320312f,
                strikethrough = 10.590909f,
                strikethroughThickness = 2.8320312f,
                TabWidth = 0.0f,
                Padding = 5.0f,
                AtlasWidth = 512,
                AtlasHeight = 512,
            });
            TMP_Glyph[] glyphs = {
                new TMP_Glyph() {
                    id = 32,
                    x = 6.0f,
                    y = 517.0f,
                    width = 0.0f,
                    height = 0.0f,
                    xOffset = 0.0f,
                    yOffset = 0.0f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 33,
                    x = 364.0f,
                    y = 47.0f,
                    width = 5.125f,
                    height = 30.0f,
                    xOffset = 4.0f,
                    yOffset = 29.25f,
                    xAdvance = 13.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 34,
                    x = 44.0f,
                    y = 104.0f,
                    width = 9.1875f,
                    height = 10.875f,
                    xOffset = 1.6875f,
                    yOffset = 28.0625f,
                    xAdvance = 12.5625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 35,
                    x = 202.0f,
                    y = 354.0f,
                    width = 28.0f,
                    height = 28.625f,
                    xOffset = 1.375f,
                    yOffset = 28.5f,
                    xAdvance = 30.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 36,
                    x = 448.0f,
                    y = 127.0f,
                    width = 18.5f,
                    height = 34.3125f,
                    xOffset = 2.625f,
                    yOffset = 31.0f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 37,
                    x = 337.0f,
                    y = 476.0f,
                    width = 29.5f,
                    height = 29.625f,
                    xOffset = 1.125f,
                    yOffset = 28.875f,
                    xAdvance = 31.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 38,
                    x = 454.0f,
                    y = 427.0f,
                    width = 25.4375f,
                    height = 29.25f,
                    xOffset = 1.1875f,
                    yOffset = 28.5625f,
                    xAdvance = 26.8125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 39,
                    x = 341.0f,
                    y = 298.0f,
                    width = 3.1875f,
                    height = 10.875f,
                    xOffset = 1.6875f,
                    yOffset = 28.0625f,
                    xAdvance = 6.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 40,
                    x = 6.0f,
                    y = 76.0f,
                    width = 7.8125f,
                    height = 38.625f,
                    xOffset = 3.3125f,
                    yOffset = 29.9375f,
                    xAdvance = 12.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 41,
                    x = 25.0f,
                    y = 76.0f,
                    width = 7.8125f,
                    height = 38.625f,
                    xOffset = 0.875f,
                    yOffset = 29.9375f,
                    xAdvance = 12.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 42,
                    x = 151.0f,
                    y = 54.0f,
                    width = 13.3125f,
                    height = 13.6875f,
                    xOffset = 2.0625f,
                    yOffset = 28.625f,
                    xAdvance = 17.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 43,
                    x = 6.0f,
                    y = 177.0f,
                    width = 23.4375f,
                    height = 23.875f,
                    xOffset = 4.9375f,
                    yOffset = 23.875f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 44,
                    x = 228.0f,
                    y = 56.0f,
                    width = 7.625f,
                    height = 11.875f,
                    xOffset = 2.25f,
                    yOffset = 4.875f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 45,
                    x = 266.0f,
                    y = 64.0f,
                    width = 10.4375f,
                    height = 3.9375f,
                    xOffset = 2.875f,
                    yOffset = 11.1875f,
                    xAdvance = 16.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 46,
                    x = 473.0f,
                    y = 29.0f,
                    width = 5.125f,
                    height = 5.125f,
                    xOffset = 3.5f,
                    yOffset = 4.75f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 47,
                    x = 133.0f,
                    y = 350.0f,
                    width = 17.3125f,
                    height = 32.9375f,
                    xOffset = 0.0f,
                    yOffset = 29.25f,
                    xAdvance = 17.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 48,
                    x = 236.0f,
                    y = 311.0f,
                    width = 20.5625f,
                    height = 29.625f,
                    xOffset = 1.8125f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 49,
                    x = 140.0f,
                    y = 394.0f,
                    width = 10.1875f,
                    height = 28.3125f,
                    xOffset = 4.625f,
                    yOffset = 28.3125f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 50,
                    x = 115.0f,
                    y = 221.0f,
                    width = 19.1875f,
                    height = 28.875f,
                    xOffset = 0.8125f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 51,
                    x = 267.0f,
                    y = 252.0f,
                    width = 19.1875f,
                    height = 29.625f,
                    xOffset = 1.8125f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 52,
                    x = 129.0f,
                    y = 310.0f,
                    width = 21.4375f,
                    height = 28.875f,
                    xOffset = 0.5f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 53,
                    x = 228.0f,
                    y = 223.0f,
                    width = 19.9375f,
                    height = 29.0625f,
                    xOffset = 1.5f,
                    yOffset = 28.3125f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 54,
                    x = 197.0f,
                    y = 263.0f,
                    width = 19.5625f,
                    height = 30.6875f,
                    xOffset = 2.1875f,
                    yOffset = 29.9375f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 55,
                    x = 188.0f,
                    y = 222.0f,
                    width = 19.6875f,
                    height = 29.375f,
                    xOffset = 2.9375f,
                    yOffset = 28.3125f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 56,
                    x = 157.0f,
                    y = 221.0f,
                    width = 19.625f,
                    height = 29.625f,
                    xOffset = 2.25f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 57,
                    x = 157.0f,
                    y = 262.0f,
                    width = 19.625f,
                    height = 30.6875f,
                    xOffset = 2.0625f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 58,
                    x = 35.0f,
                    y = 46.0f,
                    width = 5.125f,
                    height = 18.4375f,
                    xOffset = 4.0f,
                    yOffset = 18.0625f,
                    xAdvance = 13.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 59,
                    x = 187.0f,
                    y = 148.0f,
                    width = 8.4375f,
                    height = 25.0625f,
                    xOffset = 2.3125f,
                    yOffset = 18.0625f,
                    xAdvance = 13.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 60,
                    x = 433.0f,
                    y = 323.0f,
                    width = 23.0f,
                    height = 22.0625f,
                    xOffset = 5.1875f,
                    yOffset = 23.0f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 61,
                    x = 363.0f,
                    y = 370.0f,
                    width = 23.375f,
                    height = 11.375f,
                    xOffset = 4.9375f,
                    yOffset = 17.625f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 62,
                    x = 483.0f,
                    y = 303.0f,
                    width = 23.0f,
                    height = 22.0625f,
                    xOffset = 5.1875f,
                    yOffset = 23.0f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 63,
                    x = 314.0f,
                    y = 47.0f,
                    width = 13.8125f,
                    height = 30.0f,
                    xOffset = 4.0f,
                    yOffset = 29.25f,
                    xAdvance = 21.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 64,
                    x = 6.0f,
                    y = 430.0f,
                    width = 36.1875f,
                    height = 34.625f,
                    xOffset = 1.9375f,
                    yOffset = 28.75f,
                    xAdvance = 40.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 65,
                    x = 246.0f,
                    y = 392.0f,
                    width = 27.6875f,
                    height = 29.75f,
                    xOffset = -0.625f,
                    yOffset = 29.75f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 66,
                    x = 290.0f,
                    y = 187.0f,
                    width = 18.3125f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 23.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 67,
                    x = 327.0f,
                    y = 387.0f,
                    width = 24.4375f,
                    height = 30.0f,
                    xOffset = 2.0625f,
                    yOffset = 29.25f,
                    xAdvance = 28.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 68,
                    x = 285.0f,
                    y = 366.0f,
                    width = 24.25f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 29.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 69,
                    x = 93.0f,
                    y = 6.0f,
                    width = 15.9375f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 70,
                    x = 120.0f,
                    y = 6.0f,
                    width = 15.9375f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 21.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 71,
                    x = 248.0f,
                    y = 433.0f,
                    width = 28.5f,
                    height = 30.0f,
                    xOffset = 2.0625f,
                    yOffset = 29.25f,
                    xAdvance = 32.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 72,
                    x = 80.0f,
                    y = 229.0f,
                    width = 23.375f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 29.9375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 73,
                    x = 372.0f,
                    y = 251.0f,
                    width = 4.625f,
                    height = 28.625f,
                    xOffset = 3.375f,
                    yOffset = 28.625f,
                    xAdvance = 11.4375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 74,
                    x = 348.0f,
                    y = 6.0f,
                    width = 12.875f,
                    height = 29.375f,
                    xOffset = 0.0625f,
                    yOffset = 28.625f,
                    xAdvance = 15.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 75,
                    x = 424.0f,
                    y = 283.0f,
                    width = 21.9375f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 24.8125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 76,
                    x = 147.0f,
                    y = 6.0f,
                    width = 15.0625f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 18.8125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 77,
                    x = 208.0f,
                    y = 475.0f,
                    width = 33.5625f,
                    height = 30.9375f,
                    xOffset = 0.5f,
                    yOffset = 29.8125f,
                    xAdvance = 34.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 78,
                    x = 417.0f,
                    y = 457.0f,
                    width = 25.5625f,
                    height = 30.875f,
                    xOffset = 3.3125f,
                    yOffset = 29.75f,
                    xAdvance = 32.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 79,
                    x = 206.0f,
                    y = 434.0f,
                    width = 30.5625f,
                    height = 30.0f,
                    xOffset = 2.0625f,
                    yOffset = 29.25f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 80,
                    x = 6.0f,
                    y = 6.0f,
                    width = 17.0625f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 81,
                    x = 162.0f,
                    y = 433.0f,
                    width = 32.3125f,
                    height = 31.9375f,
                    xOffset = 2.0625f,
                    yOffset = 29.25f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 82,
                    x = 76.0f,
                    y = 189.0f,
                    width = 19.6875f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 22.375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 83,
                    x = 478.0f,
                    y = 84.0f,
                    width = 18.5f,
                    height = 30.0f,
                    xOffset = 1.625f,
                    yOffset = 29.25f,
                    xAdvance = 21.9375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 84,
                    x = 41.0f,
                    y = 155.0f,
                    width = 19.8125f,
                    height = 28.625f,
                    xOffset = 0.25f,
                    yOffset = 28.625f,
                    xAdvance = 20.375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 85,
                    x = 45.0f,
                    y = 235.0f,
                    width = 23.5f,
                    height = 29.375f,
                    xOffset = 3.1875f,
                    yOffset = 28.625f,
                    xAdvance = 29.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 86,
                    x = 375.0f,
                    y = 428.0f,
                    width = 25.5f,
                    height = 29.75f,
                    xOffset = -0.375f,
                    yOffset = 28.625f,
                    xAdvance = 24.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 87,
                    x = 113.0f,
                    y = 475.0f,
                    width = 37.8125f,
                    height = 30.875f,
                    xOffset = -0.125f,
                    yOffset = 29.75f,
                    xAdvance = 37.5625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 88,
                    x = 356.0f,
                    y = 330.0f,
                    width = 22.9375f,
                    height = 28.625f,
                    xOffset = 0.0f,
                    yOffset = 28.625f,
                    xAdvance = 22.875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 89,
                    x = 241.0f,
                    y = 352.0f,
                    width = 24.125f,
                    height = 28.625f,
                    xOffset = -0.1875f,
                    yOffset = 28.625f,
                    xAdvance = 23.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 90,
                    x = 483.0f,
                    y = 263.0f,
                    width = 21.875f,
                    height = 28.625f,
                    xOffset = 0.375f,
                    yOffset = 28.625f,
                    xAdvance = 23.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 91,
                    x = 389.0f,
                    y = 8.0f,
                    width = 7.4375f,
                    height = 37.3125f,
                    xOffset = 3.875f,
                    yOffset = 29.25f,
                    xAdvance = 12.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 92,
                    x = 359.0f,
                    y = 207.0f,
                    width = 17.3125f,
                    height = 32.9375f,
                    xOffset = 0.0f,
                    yOffset = 29.25f,
                    xAdvance = 17.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 93,
                    x = 408.0f,
                    y = 8.0f,
                    width = 7.375f,
                    height = 37.3125f,
                    xOffset = 0.8125f,
                    yOffset = 29.25f,
                    xAdvance = 12.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 94,
                    x = 398.0f,
                    y = 354.0f,
                    width = 23.625f,
                    height = 10.9375f,
                    xOffset = 8.1875f,
                    yOffset = 28.5f,
                    xAdvance = 40.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 95,
                    x = 259.0f,
                    y = 237.0f,
                    width = 20.0f,
                    height = 3.375f,
                    xOffset = 0.0f,
                    yOffset = -6.0625f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 96,
                    x = 410.0f,
                    y = 59.0f,
                    width = 8.125f,
                    height = 5.3125f,
                    xOffset = 4.625f,
                    yOffset = 26.625f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 97,
                    x = 72.0f,
                    y = 156.0f,
                    width = 18.8125f,
                    height = 19.9375f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 98,
                    x = 418.0f,
                    y = 115.0f,
                    width = 18.8125f,
                    height = 31.0f,
                    xOffset = 2.9375f,
                    yOffset = 30.25f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 99,
                    x = 62.0f,
                    y = 48.0f,
                    width = 15.1875f,
                    height = 19.9375f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 18.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 100,
                    x = 478.0f,
                    y = 125.0f,
                    width = 18.8125f,
                    height = 31.0f,
                    xOffset = 1.5625f,
                    yOffset = 30.25f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 101,
                    x = 481.0f,
                    y = 167.0f,
                    width = 19.1875f,
                    height = 19.9375f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 22.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 102,
                    x = 290.0f,
                    y = 46.0f,
                    width = 12.4375f,
                    height = 30.6875f,
                    xOffset = 0.25f,
                    yOffset = 30.6875f,
                    xAdvance = 12.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 103,
                    x = 320.0f,
                    y = 163.0f,
                    width = 18.8125f,
                    height = 27.875f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 104,
                    x = 359.0f,
                    y = 165.0f,
                    width = 17.875f,
                    height = 30.25f,
                    xOffset = 2.9375f,
                    yOffset = 30.25f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 105,
                    x = 372.0f,
                    y = 6.0f,
                    width = 5.3125f,
                    height = 29.125f,
                    xOffset = 2.5625f,
                    yOffset = 29.125f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 106,
                    x = 85.0f,
                    y = 107.0f,
                    width = 5.3125f,
                    height = 37.8125f,
                    xOffset = 2.5625f,
                    yOffset = 29.125f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 107,
                    x = 320.0f,
                    y = 121.0f,
                    width = 18.0f,
                    height = 30.25f,
                    xOffset = 2.9375f,
                    yOffset = 30.25f,
                    xAdvance = 20.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 108,
                    x = 467.0f,
                    y = 315.0f,
                    width = 4.25f,
                    height = 30.25f,
                    xOffset = 3.125f,
                    yOffset = 30.25f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 109,
                    x = 295.0f,
                    y = 454.0f,
                    width = 29.3125f,
                    height = 19.1875f,
                    xOffset = 2.9375f,
                    yOffset = 19.1875f,
                    xAdvance = 35.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 110,
                    x = 319.0f,
                    y = 90.0f,
                    width = 17.875f,
                    height = 19.1875f,
                    xOffset = 2.9375f,
                    yOffset = 19.1875f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 111,
                    x = 268.0f,
                    y = 293.0f,
                    width = 20.375f,
                    height = 19.9375f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 112,
                    x = 350.0f,
                    y = 126.0f,
                    width = 18.8125f,
                    height = 27.875f,
                    xOffset = 2.9375f,
                    yOffset = 19.1875f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 113,
                    x = 380.0f,
                    y = 104.0f,
                    width = 18.8125f,
                    height = 27.875f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 114,
                    x = 89.0f,
                    y = 48.0f,
                    width = 12.3125f,
                    height = 19.1875f,
                    xOffset = 2.9375f,
                    yOffset = 19.1875f,
                    xAdvance = 14.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 115,
                    x = 457.0f,
                    y = 284.0f,
                    width = 14.9375f,
                    height = 19.9375f,
                    xOffset = 0.8125f,
                    yOffset = 19.1875f,
                    xAdvance = 17.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 116,
                    x = 188.0f,
                    y = 185.0f,
                    width = 10.75f,
                    height = 25.5f,
                    xOffset = 0.6875f,
                    yOffset = 25.5f,
                    xAdvance = 12.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 117,
                    x = 381.0f,
                    y = 57.0f,
                    width = 17.9375f,
                    height = 19.25f,
                    xOffset = 2.8125f,
                    yOffset = 18.5f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 118,
                    x = 298.0f,
                    y = 257.0f,
                    width = 19.4375f,
                    height = 19.625f,
                    xOffset = -0.25f,
                    yOffset = 18.5f,
                    xAdvance = 18.875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 119,
                    x = 295.0f,
                    y = 485.0f,
                    width = 30.5f,
                    height = 20.3125f,
                    xOffset = -0.25f,
                    yOffset = 19.1875f,
                    xAdvance = 30.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 120,
                    x = 298.0f,
                    y = 227.0f,
                    width = 19.0625f,
                    height = 18.5f,
                    xOffset = -0.5f,
                    yOffset = 18.5f,
                    xAdvance = 18.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 121,
                    x = 6.0f,
                    y = 138.0f,
                    width = 19.4375f,
                    height = 27.1875f,
                    xOffset = 0.0625f,
                    yOffset = 18.5f,
                    xAdvance = 18.875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 122,
                    x = 6.0f,
                    y = 46.0f,
                    width = 17.1875f,
                    height = 18.5f,
                    xOffset = -0.0625f,
                    yOffset = 18.5f,
                    xAdvance = 18.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 123,
                    x = 492.0f,
                    y = 469.0f,
                    width = 13.9375f,
                    height = 36.9375f,
                    xOffset = 3.125f,
                    yOffset = 28.875f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 124,
                    x = 433.0f,
                    y = 357.0f,
                    width = 3.5f,
                    height = 40.0f,
                    xOffset = 8.3125f,
                    yOffset = 30.5625f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 125,
                    x = 492.0f,
                    y = 421.0f,
                    width = 13.9375f,
                    height = 36.9375f,
                    xOffset = 2.9375f,
                    yOffset = 28.875f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 126,
                    x = 417.0f,
                    y = 499.0f,
                    width = 26.4375f,
                    height = 6.8125f,
                    xOffset = 3.5f,
                    yOffset = 15.375f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 160,
                    x = 6.0f,
                    y = 517.0f,
                    width = 0.0f,
                    height = 0.0f,
                    xOffset = 0.0f,
                    yOffset = 0.0f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 161,
                    x = 150.0f,
                    y = 180.0f,
                    width = 5.125f,
                    height = 30.0f,
                    xOffset = 4.0f,
                    yOffset = 29.25f,
                    xAdvance = 13.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 162,
                    x = 228.0f,
                    y = 186.0f,
                    width = 15.75f,
                    height = 25.8125f,
                    xOffset = 3.625f,
                    yOffset = 26.9375f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 163,
                    x = 483.0f,
                    y = 337.0f,
                    width = 22.125f,
                    height = 29.8125f,
                    xOffset = 1.4375f,
                    yOffset = 28.875f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 164,
                    x = 483.0f,
                    y = 230.0f,
                    width = 21.25f,
                    height = 21.25f,
                    xOffset = 1.5f,
                    yOffset = 27.9375f,
                    xAdvance = 24.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 165,
                    x = 41.0f,
                    y = 195.0f,
                    width = 23.6875f,
                    height = 28.375f,
                    xOffset = 0.0f,
                    yOffset = 28.375f,
                    xAdvance = 24.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 166,
                    x = 341.0f,
                    y = 320.0f,
                    width = 3.5f,
                    height = 34.8125f,
                    xOffset = 8.3125f,
                    yOffset = 28.0f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 167,
                    x = 329.0f,
                    y = 202.0f,
                    width = 18.0625f,
                    height = 38.0625f,
                    xOffset = 1.625f,
                    yOffset = 29.25f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 168,
                    x = 378.0f,
                    y = 88.0f,
                    width = 11.8125f,
                    height = 4.75f,
                    xOffset = 4.0625f,
                    yOffset = 26.875f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 169,
                    x = 206.0f,
                    y = 394.0f,
                    width = 28.9375f,
                    height = 28.9375f,
                    xOffset = 2.1875f,
                    yOffset = 28.75f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 170,
                    x = 457.0f,
                    y = 259.0f,
                    width = 14.125f,
                    height = 13.875f,
                    xOffset = 1.125f,
                    yOffset = 29.0625f,
                    xAdvance = 17.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 171,
                    x = 490.0f,
                    y = 9.0f,
                    width = 15.125f,
                    height = 15.9375f,
                    xOffset = 1.5625f,
                    yOffset = 17.125f,
                    xAdvance = 18.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 172,
                    x = 321.0f,
                    y = 366.0f,
                    width = 23.375f,
                    height = 9.8125f,
                    xOffset = 4.9375f,
                    yOffset = 16.8125f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 173,
                    x = 266.0f,
                    y = 49.0f,
                    width = 10.4375f,
                    height = 3.9375f,
                    xOffset = 2.875f,
                    yOffset = 11.1875f,
                    xAdvance = 16.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 174,
                    x = 162.0f,
                    y = 393.0f,
                    width = 28.9375f,
                    height = 28.9375f,
                    xOffset = 2.1875f,
                    yOffset = 28.75f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 175,
                    x = 150.0f,
                    y = 166.0f,
                    width = 10.25f,
                    height = 2.75f,
                    xOffset = 4.875f,
                    yOffset = 25.25f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 176,
                    x = 102.0f,
                    y = 166.0f,
                    width = 11.5f,
                    height = 11.5625f,
                    xOffset = 0.8125f,
                    yOffset = 28.5f,
                    xAdvance = 13.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 177,
                    x = 363.0f,
                    y = 393.0f,
                    width = 23.4375f,
                    height = 23.3125f,
                    xOffset = 4.9375f,
                    yOffset = 23.5625f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 178,
                    x = 37.0f,
                    y = 126.0f,
                    width = 12.6875f,
                    height = 17.3125f,
                    xOffset = 0.5625f,
                    yOffset = 28.5625f,
                    xAdvance = 15.9375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 179,
                    x = 61.0f,
                    y = 126.0f,
                    width = 12.6875f,
                    height = 17.75f,
                    xOffset = 1.1875f,
                    yOffset = 28.5625f,
                    xAdvance = 15.9375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 180,
                    x = 65.0f,
                    y = 109.0f,
                    width = 8.125f,
                    height = 5.3125f,
                    xOffset = 7.25f,
                    yOffset = 26.625f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 181,
                    x = 6.0f,
                    y = 212.0f,
                    width = 23.625f,
                    height = 29.5f,
                    xOffset = -1.8125f,
                    yOffset = 21.125f,
                    xAdvance = 23.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 182,
                    x = 35.0f,
                    y = 6.0f,
                    width = 17.9375f,
                    height = 28.875f,
                    xOffset = 1.0625f,
                    yOffset = 28.875f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 183,
                    x = 473.0f,
                    y = 12.0f,
                    width = 5.125f,
                    height = 5.125f,
                    xOffset = 3.5f,
                    yOffset = 16.625f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 184,
                    x = 290.0f,
                    y = 90.0f,
                    width = 9.6875f,
                    height = 8.4375f,
                    xOffset = 5.375f,
                    yOffset = 0.0f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 185,
                    x = 44.0f,
                    y = 76.0f,
                    width = 6.6875f,
                    height = 17.0f,
                    xOffset = 3.0625f,
                    yOffset = 28.25f,
                    xAdvance = 15.9375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 186,
                    x = 62.0f,
                    y = 79.0f,
                    width = 15.3125f,
                    height = 13.9375f,
                    xOffset = 1.125f,
                    yOffset = 29.0625f,
                    xAdvance = 17.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 187,
                    x = 89.0f,
                    y = 80.0f,
                    width = 15.125f,
                    height = 15.9375f,
                    xOffset = 1.625f,
                    yOffset = 17.125f,
                    xAdvance = 18.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 188,
                    x = 111.0f,
                    y = 434.0f,
                    width = 32.8125f,
                    height = 29.625f,
                    xOffset = 2.9375f,
                    yOffset = 28.875f,
                    xAdvance = 37.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 189,
                    x = 54.0f,
                    y = 422.0f,
                    width = 31.625f,
                    height = 29.625f,
                    xOffset = 2.9375f,
                    yOffset = 28.875f,
                    xAdvance = 37.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 190,
                    x = 162.0f,
                    y = 476.0f,
                    width = 34.5625f,
                    height = 29.625f,
                    xOffset = 1.1875f,
                    yOffset = 28.875f,
                    xAdvance = 37.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 191,
                    x = 339.0f,
                    y = 47.0f,
                    width = 13.8125f,
                    height = 30.0f,
                    xOffset = 3.75f,
                    yOffset = 29.25f,
                    xAdvance = 21.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 192,
                    x = 48.0f,
                    y = 276.0f,
                    width = 27.6875f,
                    height = 36.6875f,
                    xOffset = -0.625f,
                    yOffset = 36.6875f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 193,
                    x = 6.0f,
                    y = 253.0f,
                    width = 27.6875f,
                    height = 36.6875f,
                    xOffset = -0.625f,
                    yOffset = 36.6875f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 194,
                    x = 378.0f,
                    y = 469.0f,
                    width = 27.6875f,
                    height = 36.6875f,
                    xOffset = -0.625f,
                    yOffset = 36.6875f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 195,
                    x = 336.0f,
                    y = 428.0f,
                    width = 27.6875f,
                    height = 36.3125f,
                    xOffset = -0.625f,
                    yOffset = 36.3125f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 196,
                    x = 288.0f,
                    y = 406.0f,
                    width = 27.6875f,
                    height = 36.9375f,
                    xOffset = -0.625f,
                    yOffset = 36.9375f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 197,
                    x = 90.0f,
                    y = 318.0f,
                    width = 27.6875f,
                    height = 38.5625f,
                    xOffset = -0.625f,
                    yOffset = 38.5625f,
                    xAdvance = 26.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 198,
                    x = 62.0f,
                    y = 463.0f,
                    width = 37.375f,
                    height = 28.625f,
                    xOffset = -0.625f,
                    yOffset = 28.625f,
                    xAdvance = 36.4375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 199,
                    x = 412.0f,
                    y = 408.0f,
                    width = 24.4375f,
                    height = 37.6875f,
                    xOffset = 2.0625f,
                    yOffset = 29.25f,
                    xAdvance = 28.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 200,
                    x = 263.0f,
                    y = 175.0f,
                    width = 15.9375f,
                    height = 36.6875f,
                    xOffset = 3.3125f,
                    yOffset = 36.6875f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 201,
                    x = 263.0f,
                    y = 127.0f,
                    width = 15.9375f,
                    height = 36.6875f,
                    xOffset = 3.3125f,
                    yOffset = 36.6875f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 202,
                    x = 263.0f,
                    y = 79.0f,
                    width = 15.9375f,
                    height = 36.6875f,
                    xOffset = 3.3125f,
                    yOffset = 36.6875f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 203,
                    x = 490.0f,
                    y = 36.0f,
                    width = 15.9375f,
                    height = 36.9375f,
                    xOffset = 3.3125f,
                    yOffset = 36.9375f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 204,
                    x = 130.0f,
                    y = 173.0f,
                    width = 8.125f,
                    height = 36.6875f,
                    xOffset = 0.375f,
                    yOffset = 36.6875f,
                    xAdvance = 11.4375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 205,
                    x = 148.0f,
                    y = 115.0f,
                    width = 8.125f,
                    height = 36.6875f,
                    xOffset = 3.0f,
                    yOffset = 36.6875f,
                    xAdvance = 11.4375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 206,
                    x = 102.0f,
                    y = 115.0f,
                    width = 11.625f,
                    height = 36.6875f,
                    xOffset = -0.0625f,
                    yOffset = 36.6875f,
                    xAdvance = 11.4375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 207,
                    x = 125.0f,
                    y = 115.0f,
                    width = 11.8125f,
                    height = 36.9375f,
                    xOffset = -0.1875f,
                    yOffset = 36.9375f,
                    xAdvance = 11.4375f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 208,
                    x = 162.0f,
                    y = 353.0f,
                    width = 27.8125f,
                    height = 28.625f,
                    xOffset = 0.0f,
                    yOffset = 28.625f,
                    xAdvance = 29.875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 209,
                    x = 455.0f,
                    y = 468.0f,
                    width = 25.5625f,
                    height = 37.4375f,
                    xOffset = 3.3125f,
                    yOffset = 36.3125f,
                    xAdvance = 32.125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 210,
                    x = 49.0f,
                    y = 373.0f,
                    width = 30.5625f,
                    height = 37.4375f,
                    xOffset = 2.0625f,
                    yOffset = 36.6875f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 211,
                    x = 6.0f,
                    y = 350.0f,
                    width = 30.5625f,
                    height = 37.4375f,
                    xOffset = 2.0625f,
                    yOffset = 36.6875f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 212,
                    x = 91.0f,
                    y = 368.0f,
                    width = 30.5625f,
                    height = 37.4375f,
                    xOffset = 2.0625f,
                    yOffset = 36.6875f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 213,
                    x = 48.0f,
                    y = 324.0f,
                    width = 30.5625f,
                    height = 37.0625f,
                    xOffset = 2.0625f,
                    yOffset = 36.3125f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 214,
                    x = 6.0f,
                    y = 301.0f,
                    width = 30.5625f,
                    height = 37.6875f,
                    xOffset = 2.0625f,
                    yOffset = 36.9375f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 215,
                    x = 390.0f,
                    y = 320.0f,
                    width = 22.5f,
                    height = 22.5625f,
                    xOffset = 5.625f,
                    yOffset = 23.1875f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 216,
                    x = 253.0f,
                    y = 474.0f,
                    width = 30.5625f,
                    height = 31.4375f,
                    xOffset = 2.0625f,
                    yOffset = 30.0625f,
                    xAdvance = 34.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 217,
                    x = 201.0f,
                    y = 305.0f,
                    width = 23.5f,
                    height = 37.4375f,
                    xOffset = 3.1875f,
                    yOffset = 36.6875f,
                    xAdvance = 29.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 218,
                    x = 162.0f,
                    y = 304.0f,
                    width = 23.5f,
                    height = 37.4375f,
                    xOffset = 3.1875f,
                    yOffset = 36.6875f,
                    xAdvance = 29.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 219,
                    x = 87.0f,
                    y = 269.0f,
                    width = 23.5f,
                    height = 37.4375f,
                    xOffset = 3.1875f,
                    yOffset = 36.6875f,
                    xAdvance = 29.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 220,
                    x = 122.0f,
                    y = 261.0f,
                    width = 23.5f,
                    height = 37.6875f,
                    xOffset = 3.1875f,
                    yOffset = 36.9375f,
                    xAdvance = 29.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 221,
                    x = 448.0f,
                    y = 379.0f,
                    width = 24.125f,
                    height = 36.6875f,
                    xOffset = -0.1875f,
                    yOffset = 36.6875f,
                    xAdvance = 23.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 222,
                    x = 64.0f,
                    y = 6.0f,
                    width = 17.0625f,
                    height = 28.625f,
                    xOffset = 3.3125f,
                    yOffset = 28.625f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 223,
                    x = 484.0f,
                    y = 378.0f,
                    width = 21.5f,
                    height = 31.4375f,
                    xOffset = 0.875f,
                    yOffset = 30.6875f,
                    xAdvance = 24.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 224,
                    x = 410.0f,
                    y = 76.0f,
                    width = 18.8125f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 225,
                    x = 440.0f,
                    y = 46.0f,
                    width = 18.8125f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 226,
                    x = 174.0f,
                    y = 7.0f,
                    width = 18.8125f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 227,
                    x = 290.0f,
                    y = 149.0f,
                    width = 18.8125f,
                    height = 27.0f,
                    xOffset = 1.5625f,
                    yOffset = 26.25f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 228,
                    x = 204.0f,
                    y = 7.0f,
                    width = 18.8125f,
                    height = 27.625f,
                    xOffset = 1.5625f,
                    yOffset = 26.875f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 229,
                    x = 448.0f,
                    y = 85.0f,
                    width = 18.8125f,
                    height = 30.5f,
                    xOffset = 1.5625f,
                    yOffset = 29.75f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 230,
                    x = 6.0f,
                    y = 399.0f,
                    width = 31.4375f,
                    height = 19.9375f,
                    xOffset = 1.375f,
                    yOffset = 19.1875f,
                    xAdvance = 34.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 231,
                    x = 321.0f,
                    y = 7.0f,
                    width = 15.1875f,
                    height = 27.625f,
                    xOffset = 1.5625f,
                    yOffset = 19.1875f,
                    xAdvance = 18.1875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 232,
                    x = 341.0f,
                    y = 252.0f,
                    width = 19.1875f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 22.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 233,
                    x = 388.0f,
                    y = 242.0f,
                    width = 19.1875f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 22.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 234,
                    x = 419.0f,
                    y = 206.0f,
                    width = 19.1875f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 22.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 235,
                    x = 450.0f,
                    y = 173.0f,
                    width = 19.1875f,
                    height = 27.625f,
                    xOffset = 1.5625f,
                    yOffset = 26.875f,
                    xAdvance = 22.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 236,
                    x = 470.0f,
                    y = 46.0f,
                    width = 8.125f,
                    height = 26.625f,
                    xOffset = -0.125f,
                    yOffset = 26.625f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 237,
                    x = 167.0f,
                    y = 183.0f,
                    width = 8.125f,
                    height = 26.625f,
                    xOffset = 2.5f,
                    yOffset = 26.625f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 238,
                    x = 427.0f,
                    y = 8.0f,
                    width = 11.625f,
                    height = 26.625f,
                    xOffset = -0.5625f,
                    yOffset = 26.625f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 239,
                    x = 450.0f,
                    y = 8.0f,
                    width = 11.8125f,
                    height = 26.875f,
                    xOffset = -0.6875f,
                    yOffset = 26.875f,
                    xAdvance = 10.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 240,
                    x = 277.0f,
                    y = 324.0f,
                    width = 20.375f,
                    height = 30.9375f,
                    xOffset = 1.5625f,
                    yOffset = 30.1875f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 241,
                    x = 349.0f,
                    y = 88.0f,
                    width = 17.875f,
                    height = 26.25f,
                    xOffset = 2.9375f,
                    yOffset = 26.25f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 242,
                    x = 309.0f,
                    y = 327.0f,
                    width = 20.375f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 243,
                    x = 309.0f,
                    y = 288.0f,
                    width = 20.375f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 244,
                    x = 356.0f,
                    y = 291.0f,
                    width = 20.375f,
                    height = 27.375f,
                    xOffset = 1.5625f,
                    yOffset = 26.625f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 245,
                    x = 420.0f,
                    y = 245.0f,
                    width = 20.375f,
                    height = 27.0f,
                    xOffset = 1.5625f,
                    yOffset = 26.25f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 246,
                    x = 388.0f,
                    y = 281.0f,
                    width = 20.375f,
                    height = 27.625f,
                    xOffset = 1.5625f,
                    yOffset = 26.875f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 247,
                    x = 398.0f,
                    y = 376.0f,
                    width = 23.5f,
                    height = 20.25f,
                    xOffset = 4.9375f,
                    yOffset = 22.0625f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 248,
                    x = 483.0f,
                    y = 198.0f,
                    width = 20.8125f,
                    height = 20.4375f,
                    xOffset = 1.375f,
                    yOffset = 19.5f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 249,
                    x = 234.0f,
                    y = 7.0f,
                    width = 17.9375f,
                    height = 27.375f,
                    xOffset = 2.8125f,
                    yOffset = 26.625f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 250,
                    x = 290.0f,
                    y = 110.0f,
                    width = 17.9375f,
                    height = 27.375f,
                    xOffset = 2.8125f,
                    yOffset = 26.625f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 251,
                    x = 263.0f,
                    y = 7.0f,
                    width = 17.9375f,
                    height = 27.375f,
                    xOffset = 2.8125f,
                    yOffset = 26.625f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 252,
                    x = 292.0f,
                    y = 7.0f,
                    width = 17.9375f,
                    height = 27.625f,
                    xOffset = 2.8125f,
                    yOffset = 26.875f,
                    xAdvance = 23.5f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 253,
                    x = 452.0f,
                    y = 212.0f,
                    width = 19.4375f,
                    height = 35.3125f,
                    xOffset = 0.0625f,
                    yOffset = 26.625f,
                    xAdvance = 18.875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 254,
                    x = 388.0f,
                    y = 192.0f,
                    width = 18.8125f,
                    height = 38.9375f,
                    xOffset = 2.9375f,
                    yOffset = 30.25f,
                    xAdvance = 23.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 255,
                    x = 236.0f,
                    y = 264.0f,
                    width = 19.4375f,
                    height = 35.5625f,
                    xOffset = 0.0625f,
                    yOffset = 26.875f,
                    xAdvance = 18.875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8211,
                    x = 259.0f,
                    y = 223.0f,
                    width = 20.0f,
                    height = 2.875f,
                    xOffset = 0.0f,
                    yOffset = 10.6875f,
                    xAdvance = 20.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8212,
                    x = 62.0f,
                    y = 503.0f,
                    width = 40.0f,
                    height = 2.875f,
                    xOffset = 0.0f,
                    yOffset = 10.6875f,
                    xAdvance = 40.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8216,
                    x = 247.0f,
                    y = 56.0f,
                    width = 7.3125f,
                    height = 11.5f,
                    xOffset = 2.375f,
                    yOffset = 29.25f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8217,
                    x = 116.0f,
                    y = 92.0f,
                    width = 7.3125f,
                    height = 11.5f,
                    xOffset = 2.375f,
                    yOffset = 29.25f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8218,
                    x = 135.0f,
                    y = 92.0f,
                    width = 7.3125f,
                    height = 11.5f,
                    xOffset = 2.375f,
                    yOffset = 4.8125f,
                    xAdvance = 12.0625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8220,
                    x = 176.0f,
                    y = 56.0f,
                    width = 14.375f,
                    height = 11.5f,
                    xOffset = 1.625f,
                    yOffset = 29.25f,
                    xAdvance = 17.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8221,
                    x = 202.0f,
                    y = 56.0f,
                    width = 14.375f,
                    height = 11.5f,
                    xOffset = 1.625f,
                    yOffset = 29.25f,
                    xAdvance = 17.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8222,
                    x = 228.0f,
                    y = 163.0f,
                    width = 14.375f,
                    height = 11.5f,
                    xOffset = 1.625f,
                    yOffset = 4.8125f,
                    xAdvance = 17.6875f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8224,
                    x = 418.0f,
                    y = 157.0f,
                    width = 18.0625f,
                    height = 37.3125f,
                    xOffset = 1.625f,
                    yOffset = 28.625f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8225,
                    x = 388.0f,
                    y = 143.0f,
                    width = 18.125f,
                    height = 37.3125f,
                    xOffset = 1.5625f,
                    yOffset = 28.625f,
                    xAdvance = 21.3125f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8226,
                    x = 107.0f,
                    y = 198.0f,
                    width = 11.5625f,
                    height = 11.5625f,
                    xOffset = 6.0f,
                    yOffset = 20.625f,
                    xAdvance = 23.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8230,
                    x = 97.0f,
                    y = 417.0f,
                    width = 31.8125f,
                    height = 5.125f,
                    xOffset = 4.125f,
                    yOffset = 4.75f,
                    xAdvance = 40.0f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8240,
                    x = 6.0f,
                    y = 476.0f,
                    width = 44.5625f,
                    height = 29.625f,
                    xOffset = 1.125f,
                    yOffset = 28.875f,
                    xAdvance = 46.75f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8249,
                    x = 113.0f,
                    y = 52.0f,
                    width = 7.6875f,
                    height = 15.9375f,
                    xOffset = 1.5625f,
                    yOffset = 17.125f,
                    xAdvance = 12.25f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8250,
                    x = 132.0f,
                    y = 52.0f,
                    width = 7.6875f,
                    height = 15.9375f,
                    xOffset = 1.5625f,
                    yOffset = 17.125f,
                    xAdvance = 10.625f,
                    scale = 1.0f,
                },
                new TMP_Glyph() {
                    id = 8482,
                    x = 448.0f,
                    y = 357.0f,
                    width = 23.375f,
                    height = 10.5625f,
                    xOffset = 4.4375f,
                    yOffset = 28.5f,
                    xAdvance = 33.3125f,
                    scale = 1.0f,
                },
            };
            tmpFont.AddGlyphInfo(glyphs);
            tmpFont.SortGlyphs();
            Texture2D tmpTexture = new Texture2D(512, 512, TextureFormat.Alpha8, false);
            tmpTexture.name = "Futura_Medium_BT_SDF Atlas";
            string textureFilePath = Path.Combine(KSPUtil.ApplicationRootPath, "GameData", KerbalVR.Globals.KERBALVR_TEXTURES_DIR, "Futura_Medium_BT_SDF_Texture.bin");
            byte[] textureBytes = File.ReadAllBytes(textureFilePath);
            NativeArray<byte> textureData = tmpTexture.GetRawTextureData<byte>();
            textureData.CopyFrom(textureBytes);
            tmpTexture.Apply();
            tmpFont.atlas = tmpTexture;
            Material tmpMaterial = new Material(Shader.Find("TextMeshPro/Distance Field"));
            tmpMaterial.name = "Futura_Medium_BT_SDF Material";
            tmpMaterial.mainTexture = tmpTexture;
            tmpFont.material = tmpMaterial;
            tmpFont.AddKerningInfo(new KerningTable());
            tmpFont.ReadFontDefinition();
            return tmpFont;
        }
    }
}
